on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            S6_ARCH: amd64
          - platform: linux/arm/v7
            S6_ARCH: armhf
          - platform: linux/arm64
            S6_ARCH: aarch64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        build-args: S6_ARCH=${{ matrix.S6_ARCH }}
        tags: xuantran94/cloudflare-ddns-telegram:${{ matrix.platform }}
        platforms: ${{ matrix.platform }}