#!/usr/bin/with-contenv sh

. /app/cloudflare.sh
. /config/cloudflare.conf

# Your Telegram Bot API Token
TOKEN=$YOUR_BOT_TOKEN
# Chat ID of the recipient
CHAT_ID=$RECIPIENT_CHAT_ID
URL="https://api.telegram.org/bot$TOKEN/sendMessage"

DnsIpAddress=$(getDnsRecordIp $CF_ZONE_ID $CF_RECORD_ID)

if [ ! -z ${CUSTOM_LOOKUP_CMD+x} ]; then
  CurrentIpAddress=$(getCustomIpAddress)
elif [ ! -z ${INTERFACE+x} ]; then
  CurrentIpAddress=$(getLocalIpAddress)
else
  CurrentIpAddress=$(getPublicIpAddress)
fi
# msg =""
if [ "$CurrentIpAddress" != "$DnsIpAddress" ]; then
  echo "Updating CloudFlare DNS record $CF_RECORD_NAME from $DnsIpAddress to $CurrentIpAddress..."
  update=$(updateDnsRecord $CF_ZONE_ID $CF_RECORD_ID $CF_RECORD_NAME $CurrentIpAddress)

  if [ "$update" == "null" ]; then
    msg="ERROR: Failed to update CloudFlare DNS record $CF_RECORD_NAME from $DnsIpAddress to $CurrentIpAddress"
  else
    msg="CloudFlare DNS record $CF_RECORD_NAME ($CurrentIpAddress) updated successfully."
  fi
  echo $msg
  curl -s -X POST $URL -d chat_id=$CHAT_ID -d text="$msg"
else
  msg="No DNS update required for $CF_RECORD_NAME ($DnsIpAddress)."
fi
echo $msg

